import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

def get_color(value, min_value, max_value, color_scale):
    if value is None:
        return '#000000'
    normalized = (value - min_value) / (max_value - min_value)
    cmap = plt.get_cmap(color_scale)
    color = mcolors.to_hex(cmap(normalized))
    return color

basemaps = {'OSM': 'http://tile.openstreetmap.org/{z}/{x}/{y}.png', 'Google-Satellite': 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
            'Google-Road': 'https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}', 'ESRI': 'http://services.arcgisonline.com/ArcGis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png',
            'Google-Hybrid': 'https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}', 'OpenTopo': 'http://c.tile.opentopomap.org/{z}/{x}/{y}.png'}


colormap_scales = {
    "Perceptually Uniform Sequential - Viridis": "viridis",
    "Perceptually Uniform Sequential - Plasma": "plasma",
    "Perceptually Uniform Sequential - Inferno": "inferno",
    "Perceptually Uniform Sequential - Magma": "magma",
    "Perceptually Uniform Sequential - Cividis": "cividis",
    "Sequential - Greys": "Greys",
    "Sequential - Purples": "Purples",
    "Sequential - Blues": "Blues",
    "Sequential - Greens": "Greens",
    "Sequential - Oranges": "Oranges",
    "Sequential - Reds": "Reds",
    "Sequential - Yellow-Orange-Brown": "YlOrBr",
    "Sequential - Yellow-Orange-Red": "YlOrRd",
    "Sequential - Orange-Red": "OrRd",
    "Sequential - Purple-Red": "PuRd",
    "Sequential - Red-Purple": "RdPu",
    "Sequential - Blue-Purple": "BuPu",
    "Sequential - Green-Blue": "GnBu",
    "Sequential - Purple-Blue": "PuBu",
    "Sequential - Yellow-Green-Blue": "YlGnBu",
    "Sequential - Purple-Blue-Green": "PuBuGn",
    "Sequential - Blue-Green": "BuGn",
    "Sequential - Yellow-Green": "YlGn",
    "Sequential (2) - Binary": "binary",
    "Sequential (2) - Gist Yarg": "gist_yarg",
    "Sequential (2) - Gist Gray": "gist_gray",
    "Sequential (2) - Gray": "gray",
    "Sequential (2) - Bone": "bone",
    "Sequential (2) - Pink": "pink",
    "Sequential (2) - Spring": "spring",
    "Sequential (2) - Summer": "summer",
    "Sequential (2) - Autumn": "autumn",
    "Sequential (2) - Winter": "winter",
    "Sequential (2) - Cool": "cool",
    "Sequential (2) - Wistia": "Wistia",
    "Sequential (2) - Hot": "hot",
    "Sequential (2) - Afmhot": "afmhot",
    "Sequential (2) - Gist Heat": "gist_heat",
    "Sequential (2) - Copper": "copper",
    "Diverging - PiYG": "PiYG",
    "Diverging - PRGn": "PRGn",
    "Diverging - BrBG": "BrBG",
    "Diverging - PuOr": "PuOr",
    "Diverging - RdGy": "RdGy",
    "Diverging - RdBu": "RdBu",
    "Diverging - Red-Yellow-Blue": "RdYlBu",
    "Diverging - Red-Yellow-Green": "RdYlGn",
    "Diverging - Spectral": "Spectral",
    "Diverging - Coolwarm": "coolwarm",
    "Diverging - Blue-White-Red": "bwr",
    "Diverging - Seismic": "seismic",
    "Cyclic - Twilight": "twilight",
    "Cyclic - Twilight Shifted": "twilight_shifted",
    "Cyclic - HSV": "hsv",
    "Qualitative - Pastel1": "Pastel1",
    "Qualitative - Pastel2": "Pastel2",
    "Qualitative - Paired": "Paired",
    "Qualitative - Accent": "Accent",
    "Qualitative - Dark2": "Dark2",
    "Qualitative - Set1": "Set1",
    "Qualitative - Set2": "Set2",
    "Qualitative - Set3": "Set3",
    "Qualitative - Tab10": "tab10",
    "Qualitative - Tab20": "tab20",
    "Qualitative - Tab20b": "tab20b",
    "Qualitative - Tab20c": "tab20c",
    "Miscellaneous - Flag": "flag",
    "Miscellaneous - Prism": "prism",
    "Miscellaneous - Ocean": "ocean",
    "Miscellaneous - Gist Earth": "gist_earth",
    "Miscellaneous - Terrain": "terrain",
    "Miscellaneous - Gist Stern": "gist_stern",
    "Miscellaneous - Gnuplot": "gnuplot",
    "Miscellaneous - Gnuplot2": "gnuplot2",
    "Miscellaneous - CMRmap": "CMRmap",
    "Miscellaneous - Cubehelix": "cubehelix",
    "Miscellaneous - BRG": "brg",
    "Miscellaneous - HSV": "hsv",
    "Miscellaneous - Gist Rainbow": "gist_rainbow",
    "Miscellaneous - Rainbow": "rainbow",
    "Miscellaneous - Jet": "jet",
    "Miscellaneous - Nipy Spectral": "nipy_spectral",
    "Miscellaneous - Gist Ncar": "gist_ncar"
}